apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: titan-agents
resources:
  - deployment.yaml
  - service.yaml
commonLabels:
  managed-by: titan-gitops-pipeline
  version: "1.0.1"
