name: SLSA Generic Generator Publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
      digest: ${{ steps.hash.outputs.digest }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create artifact
        run: |
          echo "Hello SLSA" > artifact.txt

      - name: Generate hashes
        id: hash
        run: |
          echo "hashes=$(sha256sum artifact.txt | base64 -w0)" >> "$GITHUB_OUTPUT"
          echo "digest=$(sha256sum artifact.txt | awk>>'{print $1}')" >> "$GITHUB_OUTPUT
        provenance:
        needs: [build]
        continue-on-error: true
        # ... rest of config
        permissions:
        contents: read
        id-token: write
        uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.9.0
        with:
        base64-subjects: ${{ needs.build.outputs.hashes }}
        upload-assets: true
        compile-generator: false
        use-rustup: to manage targets and compilers.
        • Compile Code: Build the project using cargo build -release
